version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    user: 1000:1000
    group_add:
      - "109" # render group
    volumes:
      - /home/jesus/containers/jellyfin/cache:/cache
      - /home/jesus/containers/jellyfin/config:/config
      - /home/jesus/data/media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

  radarr:
    container_name: radarr
    network_mode: 'host'
    image: ghcr.io/hotio/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/radarr:/config
      - /home/jesus/data:/data

  sonarr:
    container_name: sonarr
    network_mode: 'host'
    image: ghcr.io/hotio/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/sonarr:/config
      - /home/jesus/data:/data
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    network_mode: 'host'
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/jesus/containers/qbittorrent:/config
      - /home/jesus/data/torrents:/data/torrents
    restart: unless-stopped

  jackett:
    container_name: jackett
    network_mode: 'host'
    image: ghcr.io/hotio/jackett
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/jackett:/config
      - /home/jesus/data/torrents:/downloads
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    network_mode: 'host'
    image: ghcr.io/flaresolverr/flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC-5
    restart: unless-stopped

  nginx:
    container_name: nginx
    network_mode: 'host'
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - /home/jesus/containers/nginx/data:/data
      - /home/jesus/containers/nginx/letsencrypt:/etc/letsencrypt
