version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/jesus/containers/jellyfin:/config
      - /home/jesus/media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.12
    extra_hosts:
      - "host.docker.internal:host-gateway"

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/radarr:/config
      - /home/jesus/data:/data

  sonarr:
    image: ghcr.io/hotio/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/sonarr:/config
      - /home/jesus/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/jesus/containers/qbittorrent:/config
      - /home/jesus/data/torrents:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  jackett:
    image: ghcr.io/hotio/jackett
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC-5
    volumes:
      - /home/jesus/containers/jackett:/config
      - /home/jesus/downloads/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
